---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana
  labels:
    prometheus: prometheus
spec:
  selector:
    matchLabels:
      app: grafana
  endpoints:
    - port: web
