---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  labels:
    prometheus: prometheus
spec:
  selector:
    matchLabels:
      operated-prometheus: "true"
  endpoints:
    - port: web
