---
grafana: 
  enabled: false
prometheus:
  prometheusSpec:
    replicas: 1
    externalUrl: http://localhost:8080/prometheus
alertmanager:
  alertmanagerSpec:
    replicas: 1
    externalUrl: http://localhost:8080/alertmanager